name: CI test to build and run tests for MYNN SFC scheme on ubuntu v22.04

on: [pull_request,workflow_dispatch,push]

jobs:
  run_driver:

    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        fortran-compiler: [gfortran-12]

    # Environmental variables
    env:
      driver_ROOT: /home/runner/work/MYNN-SFC/MYNN-SFC

    # Workflow steps
    steps:

    - name: Checkout code (into ${driver_ROOT})
      uses: actions/checkout@v3

    - name: Build unit tests
      run: |
        cd ${driver_ROOT}/tests
        make driver

    - name: Run unit tests
      run: |
        cd ${driver_ROOT}/tests
        ./driver

    - name: Generate code coverage report
      run: |
        cd ${driver_ROOT}/tests
        gcov -o . ../module_sf_mynnsfc.F90 ../module_sf_mynnsfc_land.F90 \
           ../module_sf_mynnsfc_water.F90 ../module_sf_mynnsfc_ice.F90 \
           ../WRF/module_sf_mynnsfc_driver.F90
           #gcovr --root .. -g --filter '.*/module_sf_mynnsfc.*\.F90' --exclude '.*/tests/.*' .
